name: build
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: dev
        description: "specify branch"
  push:
    branches: [dev] 
        
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: printbranch name
        run: echo ${{github.event.inputs.branch}}
        
      - name:  building
        run: |
          echo "buildin application"
           echo ${{ github.workspace }}
           echo  GITHUB_REPOSITORY 
        
        
      - name: done build
        run: echo "done with build"
        
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: deploy to cloud
        run: echo "deploying"
      - id: deploment-result
        run: echo "success"
      - name: deploy job
        if: ${{steps.deploy-result.outcome}} == 'success'
        run: echo "successfully completed cicd"
        
    
       
      
        
