name: build
on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        default: master
        description: "specify branch"
        
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name:  building
        run: echo "buildin application"
        
        
      - name: done build
        run: echo "done with build"
        
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: deploy to cloud
        run: echo "deploying"
      - id: deploment-result
        run: echo "success"
      - name: deploy job
        if: github.event.deploy-result.outcome == 'success'
        run: echo "successfully completed cicd"
        
    
       
      
        
