name: build
on:
  workflow_dispatch:
    inputs:
      branch:
        description:  specify Branch name
        required: true
        default: develop

      Manifest-file:
        description: "specify manifest file for the environment"
        default: 'manifest-dev.yml'
      
      foundation:
        description: "PCF Foundation Name (CAC OR CAE)"
        default: 'CAC'
      
      pcforg:
        description: "PCF Organization Name"
        default: 'CDN-CAC-DEV'
      
      pcfspace:
        description: "PCF Space Name"
        default: 'GRS-WEB-CAC-DEV'
      
      springbootprofile:
        description: "Provide Spring Boot Active Profile"
        default: 'dev'
    
        
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: printbranch name
        run: echo ${{github.event.inputs.branch}}
        
      - name:  building
        run: |
          echo "buildin application"
           echo ${{ github.workspace }}
           echo  GITHUB_REPOSITORY 
        
        
      - name: done build
        run: echo "done with build"
        
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: deploy to cloud
        run: echo "deploying"
      - id: deploment-result
        run: echo "success"
      - name: deploy job
        if: ${{steps.deploy-result.outcome}} == 'success'
        run: echo "successfully completed cicd"
        
    
       
      
        
